version: '3'
services:
   jenkins:
     container_name: jenkins
     image: jenkins/jenkins
     restart: "unless-stopped"
     ports:
     - "8080:8080"
     volumes:
     - "$PWD/../jenkins_data/jenkins_home:/var/jenkins_home"
     - "/var/run/docker.sock:/var/run/docker.sock"
     build:
      context: ansible_jenkins
     networks:
     - net
   remote_host:
     container_name: remote_host
     image: remote_host
     restart: "unless-stopped"
     ports:
     - "12222:22"
     build: 
      context: ubuntu
     networks:
     - net
   mysqldb:
    container_name: mysql_db
    image: mysql:5.7
    restart: "unless-stopped"
    ports:
    - "23306:3306"
    volumes:
    - "$PWD/../jenkins_data/mysql_data:/var/lib/mysql"
    environment:
     MYSQL_ROOT_PASSWORD: "Password123"
    networks:
    - net
   gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    ports:
     - '8090:80'
     - '3222:22'
    volumes:
     - '$PWD/../jenkins_data/gitlab/config:/etc/gitlab'
     - '$PWD/../jenkins_data/gitlab/logs:/var/log/gitlab'
     - '$PWD/../jenkins_data/gitlab/data:/var/opt/gitlab'
    networks:
     - net
networks:
 net:
