pipeline{
	agent any

	environment {
		DOCKER_USER = credentials('docker_hub_user_id')
		DOCKER_PASS = credentials('docker_hub_user_pass')
}

	stages{

	stage('Build'){
		steps{
			sh """
			     ./jenkins/build/maven.sh mvn -B -DskipTests clean package
                             ./jenkins/build/build.sh 
			"""
		}

		post {
	  	success {
	 	   archiveArtifacts artifacts: 'java-app/target/*.jar', fingerprint: true
		}
		}

	}

	stage('Test'){
		steps{
			sh './jenkins/test/maven.sh mvn test'

		}
	
		post {
		always {
		  junit 'java-app/target/surefire-reports/*.xml'
		}
		}

	}

	stage('Push'){
		steps{
			sh './jenkins/push/push.sh'
			
		}
	}

	stage('Deploy'){
		steps{
			sh './jenkins/deploy/deploy.sh'
			
		}
	}
	}
}
